"""Backtest: dual-trade split strategy vs single-trade on historical signals.

Reads all closed signals from the DB (actual live signals generated by the bot)
and replays them under three strategies:
  1. SINGLE-TRADE  — one trade per signal targeting TP1 (2% risk)
  2. DUAL CONSERVATIVE — T1→TP1 WIN, T2→BREAKEVEN (after TP1); both LOSS on SL
  3. DUAL OPTIMISTIC   — T1→TP1 WIN, T2→TP2 WIN  (after TP1); both LOSS on SL

Note on MIN_LOT:
  For balances under ~$150 the 1% half-lot rounds UP to MIN_LOT (0.01) just like
  the full 2% single lot does. This means dual-trade doubles the position size
  (and risk) vs single-trade at small account sizes. The backtest shows
  this effect honestly and also shows a $1 000 starting balance where
  proper lot-splitting is possible.
"""
import sys, os, sqlite3, io
# Force UTF-8 on Windows so box/symbol chars print cleanly
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
sys.path.insert(0, r'e:\eurusd-bot')
import config

PIP  = config.PIP_SIZE
PPL  = config.PIP_VALUE_PER_LOT
MIN  = config.MIN_LOT
STEP = config.LOT_STEP
MAX  = config.MAX_LOT
INIT = config.DEMO_INITIAL_BALANCE


# ── helpers ───────────────────────────────────────────────────────────────────

def _pips(a, b):
    return abs(float(a) - float(b)) / PIP


def _lot(balance, entry, sl, risk_pct):
    sl_pips = _pips(entry, sl)
    if sl_pips < 0.5:
        return MIN
    raw = (balance * risk_pct) / (sl_pips * PPL)
    stepped = round(raw / STEP) * STEP
    return round(max(MIN, min(stepped, MAX)), 2)


def _max_drawdown(history):
    peak = history[0]
    max_dd = 0.0
    for v in history:
        if v > peak:
            peak = v
        dd = peak - v
        if dd > max_dd:
            max_dd = dd
    return round(max_dd, 2)


def _profit_factor(trades):
    gross_win  = sum(t["pnl"] for t in trades if t["pnl"] > 0)
    gross_loss = abs(sum(t["pnl"] for t in trades if t["pnl"] < 0))
    return round(gross_win / gross_loss, 2) if gross_loss > 0 else float("inf")


def _load_signals(db_path):
    if not os.path.exists(db_path):
        return []
    con = sqlite3.connect(db_path)
    cur = con.cursor()
    cur.execute("""
        SELECT id, direction, entry, sl, tp1, tp2, close_price, status
        FROM   signals
        WHERE  status IN ('WIN','LOSS')
          AND  (trade_num = 1 OR trade_num IS NULL)
        ORDER  BY id ASC
    """)
    rows = cur.fetchall()
    con.close()
    return [
        {"id": r[0], "dir": r[1],
         "entry": float(r[2] or 0), "sl": float(r[3] or 0),
         "tp1":   float(r[4] or r[6] or 0),
         "tp2":   float(r[5] or 0),
         "close": float(r[6] or 0),
         "status": r[7]}
        for r in rows
    ]


# ── per-strategy simulators ───────────────────────────────────────────────────

def sim_single(signals, init_balance):
    balance = init_balance
    history = [balance]
    trades  = []
    for s in signals:
        lot = _lot(balance, s["entry"], s["sl"], risk_pct=0.02)
        if s["status"] == "WIN":
            pnl = round(lot * _pips(s["entry"], s["tp1"]) * PPL, 2)
        else:
            pnl = -round(lot * _pips(s["entry"], s["sl"]) * PPL, 2)
        balance = round(balance + pnl, 2)
        history.append(balance)
        trades.append({"id": s["id"], "status": s["status"],
                       "pnl": pnl, "lot": lot, "t1_pnl": pnl, "t2_pnl": 0, "t2": None})
    return balance, history, trades


def sim_dual(signals, init_balance, t2_win_on_tp1=False):
    """Dual-trade simulation.

    When TP1 is hit:
      t2_win_on_tp1=False → T2 = BREAKEVEN ($0)   [conservative]
      t2_win_on_tp1=True  → T2 = WIN at TP2        [optimistic]
    """
    balance = init_balance
    history = [balance]
    trades  = []
    for s in signals:
        lot_h = _lot(balance, s["entry"], s["sl"], risk_pct=0.01)

        if s["status"] == "LOSS":
            sl_pips = _pips(s["entry"], s["sl"])
            t1_pnl  = -round(lot_h * sl_pips * PPL, 2)
            t2_pnl  = -round(lot_h * sl_pips * PPL, 2)
            t2_out  = "LOSS"
        else:
            t1_pnl = round(lot_h * _pips(s["entry"], s["tp1"]) * PPL, 2)
            if t2_win_on_tp1 and s["tp2"]:
                t2_pnl = round(lot_h * _pips(s["entry"], s["tp2"]) * PPL, 2)
                t2_out = "WIN"
            else:
                t2_pnl = 0.0
                t2_out = "BE"

        total   = round(t1_pnl + t2_pnl, 2)
        balance = round(balance + total, 2)
        history.append(balance)
        trades.append({"id": s["id"], "status": s["status"],
                       "pnl": total, "lot": lot_h,
                       "t1_pnl": t1_pnl, "t2_pnl": t2_pnl, "t2": t2_out})
    return balance, history, trades


# ── ascii chart ───────────────────────────────────────────────────────────────

def _ascii_chart(h1, h2, h3, width=58, rows=10):
    all_vals = h1 + h2 + h3
    mn, mx   = min(all_vals), max(all_vals)
    rng      = mx - mn or 1
    grid     = [[" "] * width for _ in range(rows)]

    def _plot(hist, char):
        n = len(hist)
        for i, v in enumerate(hist):
            x = int(i / max(n-1, 1) * (width - 1))
            y = rows - 1 - int((v - mn) / rng * (rows - 1))
            grid[max(0, min(rows-1, y))][x] = char

    _plot(h1, ".")  # single
    _plot(h2, "C")  # conservative
    _plot(h3, "O")  # optimistic

    init_y = rows - 1 - int((h1[0] - mn) / rng * (rows - 1))
    for i, row in enumerate(grid):
        prefix = "|" if i == init_y else " "
        print("    " + prefix + "".join(row) + "|")


# ── main report ───────────────────────────────────────────────────────────────

def report(symbol, init_balance=INIT):
    sigs = _load_signals(config.db_path(symbol))
    if not sigs:
        print(f"\n  {symbol}: no closed signals in DB — run the live bot first.")
        return

    n_total = len(sigs)
    n_win   = sum(1 for s in sigs if s["status"] == "WIN")
    n_loss  = n_total - n_win
    wr      = round(n_win / n_total * 100, 1)

    b1, h1, t1_ = sim_single(sigs, init_balance)
    b2, h2, t2_ = sim_dual(sigs, init_balance, t2_win_on_tp1=False)
    b3, h3, t3_ = sim_dual(sigs, init_balance, t2_win_on_tp1=True)

    W = 64
    bar = "─" * W

    print(f"\n  +{'='*W}+")
    lbl = f"  BACKTEST -- {symbol}   starting ${init_balance:.2f}"
    print(f"  | {lbl:<{W-1}}|")
    print(f"  +{'='*W}+")
    print(f"  Signals: {n_total}  │  TP1-WIN: {n_win}  │  SL-LOSS: {n_loss}  │  TP1 win rate: {wr}%")
    print(f"  {bar}")

    # ── Summary table ─────────────────────────────────────────────────────────
    print(f"  {'Strategy':<22} {'Final $':>9} {'P&L':>9} {'Return':>8} {'MaxDD':>8} {'PF':>6}")
    print(f"  {'─'*22} {'─'*9} {'─'*9} {'─'*8} {'─'*8} {'─'*6}")

    def _row(name, bal, hist, trades):
        pnl    = round(bal - init_balance, 2)
        ret    = round((bal / init_balance - 1) * 100, 1)
        mdd    = _max_drawdown(hist)
        pf     = _profit_factor(trades)
        pnl_s  = f"{'+' if pnl>=0 else ''}{pnl:.2f}"
        ret_s  = f"{'+' if ret>=0 else ''}{ret:.1f}%"
        return f"  {name:<22} ${bal:>8.2f} {pnl_s:>9} {ret_s:>8} ${mdd:>7.2f} {pf:>6}"

    print(_row("Single-trade",      b1, h1, t1_))
    print(_row("Dual conservative", b2, h2, t2_))
    print(_row("Dual optimistic",   b3, h3, t3_))

    # ── Per-signal table ──────────────────────────────────────────────────────
    print(f"\n  {'#':<5} {'Dir':4} {'T1':5}  {'Single':>8}  {'Dual-Con':>9}  {'Dual-Opt':>9}  T2 note")
    print(f"  {'─'*68}")
    for sig, s_t, c_t, o_t in zip(sigs, t1_, t2_, t3_):
        s_p  = f"{'+' if s_t['pnl']>=0 else ''}{s_t['pnl']:+.2f}"
        c_p  = f"{'+' if c_t['pnl']>=0 else ''}{c_t['pnl']:+.2f}"
        o_p  = f"{'+' if o_t['pnl']>=0 else ''}{o_t['pnl']:+.2f}"
        if c_t["t2"] == "BE":
            note = f"T2 BE (SL→entry $0)  /  T2 WIN +${o_t['t2_pnl']:.2f} if TP2 hit"
        elif c_t["t2"] == "LOSS":
            note = f"T2 LOSS (SL ${abs(c_t['t2_pnl']):.2f})"
        else:
            note = ""
        print(f"  #{sig['id']:<4} {sig['dir']:4} {sig['status']:<5}  {s_p:>8}  {c_p:>9}  "
              f"{o_p:>9}  {note}")
    print(f"  {'─'*68}")

    # ── ASCII balance chart ───────────────────────────────────────────────────
    print(f"\n  Balance curve  (· = single   C = dual-conservative   O = dual-optimistic)")
    hi = max(h1 + h2 + h3)
    lo = min(h1 + h2 + h3)
    print(f"    +{'-'*58}+  ${hi:.2f}")
    _ascii_chart(h1, h2, h3)
    print(f"    +{'-'*58}+  ${lo:.2f}")
    print(f"     0 signals → {n_total}")

    # ── Key insights ──────────────────────────────────────────────────────────
    print(f"\n  KEY INSIGHTS")
    print(f"  {bar}")

    # Min-lot effect check
    f_lot = _lot(init_balance, sigs[0]["entry"], sigs[0]["sl"], 0.02)
    h_lot = _lot(init_balance, sigs[0]["entry"], sigs[0]["sl"], 0.01)
    if f_lot == h_lot == MIN:
        print(f"  ⚠  MIN LOT FLOOR: At ${init_balance:.0f}, both 2% and 1% risk → {MIN} lots.")
        print(f"     Dual-trade = 2×{MIN}L = DOUBLE single-trade exposure.")
        print(f"     That's why dual-conservative shows larger losses vs single.")
        print(f"     Need ~$2 000+ balance to benefit from 1% per-trade splitting.")
    else:
        print(f"  ✓  Proper lot-split: single={f_lot}L  →  dual {h_lot}L × 2 trades")

    # Average pip stats
    win_sigs  = [s for s in sigs if s["status"] == "WIN"]
    loss_sigs = [s for s in sigs if s["status"] == "LOSS"]
    avg_tp1 = round(sum(_pips(s["entry"], s["tp1"]) for s in win_sigs)  / max(n_win, 1), 1)
    avg_tp2 = round(sum(_pips(s["entry"], s["tp2"]) for s in win_sigs if s["tp2"]) / max(n_win, 1), 1)
    avg_sl  = round(sum(_pips(s["entry"], s["sl"])  for s in loss_sigs) / max(n_loss, 1), 1)
    print(f"  Avg pips when TP1 hit: {avg_tp1:.1f} pips  │  Avg TP2 dist: {avg_tp2:.1f} pips")
    print(f"  Avg pips when SL hit:  {avg_sl:.1f} pips")

    # Break-even analysis for T2
    if n_win > 0:
        avg_t1_profit = sum(t["t1_pnl"] for t in t1_ if t["t1_pnl"] > 0) / n_win
        avg_t1_dual   = sum(t["t1_pnl"] for t in t2_ if t["t1_pnl"] > 0) / n_win
        avg_t2_win    = sum(t["t2_pnl"] for t in t3_ if t["t2_pnl"] > 0) / n_win
        gap           = avg_t1_profit - avg_t1_dual  # how much less T1 dual earns vs single
        needed_wr     = (gap / avg_t2_win * 100) if avg_t2_win > 0 else None
        if needed_wr is not None:
            pct = max(0, min(100, needed_wr))
            print(f"  T2 must reach TP2 ≥ {pct:.0f}% of TP1 wins for dual to beat single.")
    print()


if __name__ == "__main__":
    print("=" * 68)
    print("  DUAL-TRADE SPLIT STRATEGY — BACKTEST RESULTS")
    print("  Using live bot signal history from database")
    print("=" * 68)

    for sym in config.PAIRS:
        report(sym, init_balance=100.0)

    print("\n" + "=" * 68)
    print("  SAME SIGNALS WITH $1,000 BALANCE (correct lot-splitting possible)")
    print("=" * 68)
    for sym in config.PAIRS:
        report(sym, init_balance=1000.0)
